version: "3.9"

volumes:
  mongodb_data_container: {}

networks:
  mongo_database:


services:
  simple-crud-db:
    container_name: simple-crud-db
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: simple_crud
    ports:
      - 27017:27017
    networks:
      - mongo_database
    volumes:
      - mongodb_data_container:/data/db